{{ 
    config(
        materialized= "view",
        tags= ["silver", "quote_part_jade"]
    )
}}


with quote_header as (
    select * from {{ source('bronze', 'A_BRONZE_AS400_DEVENT') }}
),

quote_line as (
    select * from {{ source('bronze', 'a_bronze_as400_devlig') }}
),

header as (
    select         
        IDDOC,
        IDTIERS,
        DOCNUM,
        DOCSUFFIX1,
        DOCSUFFIX2,
        IDADRFAC,
        IDADRLIV,
        IDADRDOC,
        DATECREAT,
        HEURECREAT,
        DATEMODIF,
        HEUREMODIF,
        DATEVALID,
        HEUREVALID,
        DATEENVOI,
        HEUREENVOI,
        DATELIMIT,
        DATETARIF,
        CODECON,
        CLASSCDE,
        ETATDOC,
        ETATMSG,
        DEVVENTE,
        CODEPROMO,
        IDTIERSPROMO,
        NUMSERIE,
        COMJADIMPR,
        COMCLIENT,
        LANGUEDOC,
        COMJADINT,
        FIXDEVISE,
        FIXTARIF,
        LIVAUTO,
        FACAUTO,
        SERVICE,
        SORTEVENTE,
        TYPEVENTE,
        MARQUAGE,
        IDTRANSIT,
        POIDSTOTAL,
        VOLUMETOTAL,
        POIDSAUTO,
        VOLUMEAUTO,
        TOTALTTC,
        TOTALHTBRUTP,
        TOTALHTNETP,
        TOTALHTNET,
        TOTALFOB,
        REFDOSJAD,
        IDPAYSDEST,
        DATEDEM,
        HEUREDEM,
        NATVENTE,
        SOUHAITLIV,
        FORMSOUHAIT,
        TOTALREMISE,
        TOTALTVA,
        TOTALEURO,
        TOTALFRAIS,
        TOTALACHATPEUR,
        TOTALACHATFEUR,
        TRANSPORT,
        INCOTERM,
        LIEUINCOTERM,
        PAYSINCOTERM,
        REFCLIENT,
        CDTREGLEMENT,
        MODEREGLEMENT,
        REFGARANTIE,
        TYPEFACTURATION,
        UTILISATEUR,
        LISTETARIF,
        TRANSIT1,
        IDTRANSIT1,
        IDADRTRS1,
        TRANSIT2,
        IDTRANSIT2,
        IDADRTRS2,
        NBJOURSECHEANCE,
        QUANTIEME,
        REGLEMENTCDE,
        PAYSCOMPTA,
        IMPRDISPO,
        IMPADRFAC,
        IMPADRLIVFINALE,
        IMPADRLIV,
        PAYSORIGINE,
        PAYSPROVENANCE,
        IMPCLASSECDE,
        IMPDISPO,
        IMPHTC,
        NUMLICENCE,
        LOILME,
        INSPECTION,
        CODEIMPUTATION,
        TITREDOCUMENT,
        IMPCOLIS,
        LANGUEDETAIL,
        CLASSEDOCUMENT,
        ETATVENTEPERDU,
        RAISONVENTEPERDUENTETE,
        NPS,
        CODEDATEVALEUR,
        DATERECEPTIONPO,
        DATERELANCE,
        NBRELANCE
    from quote_header
    where DATECREAT >= '20230123'

        
),

lines as (
    select  
        IDDOCLIG,
        IDDOC,
        DOCNUM,
        DOCSUFFIX1,
        DOCSUFFIX2,
        TYPEINFO,
        CODETRF,
        VRSTRF,
        TYPELIGNE,
        POSTENUM,
        POSTESUFFIX,
        IDLIGNE,
        IDLIGNEREF,
        REFPIECE,
        LIBELLE,
        CODECLASSE,
        BASECALC,
        COEFCLIENT,
        PXUNITACHAT,
        PXUNITLIST,
        PXUNITJAD,
        PXUNITBASE,
        PXTOTACHATEUR,
        PXUNITVENTEDA,
        PXTOTVENTEEUR,
        PXUNITVENTEDV,
        PXTOTVENTEDV,
        QTECLIENT,
        QTECDE,
        QTEANNULEE,
        QTERPL,
        QTEPACK,
        PXPACK,
        DEVACHAT,
        TAUXCHANGE,
        DEVVENTE,
        ORIGINELIGNE,
        LIGNEANNULEE,
        POIDSUNITAIRE,
        POIDSTOTALLIGNE,
        POIDSPACK,
        VOLUMEUNITAIRE,
        VOLUMETOTALLIGNE,
        VOLUMEPACK,
        CODEREMISE,
        COEFREMISE,
        TOTREMISEEUR,
        REMAN,
        ERRREF,
        CODEDISPO,
        QTECDETOT,
        QTECDEFRS,
        QTELIVTOT,
        QTEFACTOT,
        CODEVENTEPERDU,
        RAISONVENTEPERDULIGNE,
        ITEMDELAILIVRAISON,
        ITEMDATELIVRAISON,
        TYPETARIF,
        REFPIECEERPCLIENT
    from quote_line
),


silver_quote_part as (
    select 
        /*
            HEADER
        */
        h.IDDOC,
        h.IDTIERS,
        h.DOCNUM,
        h.DOCSUFFIX1,
        h.DOCSUFFIX2,
        h.IDADRFAC,
        h.IDADRLIV,
        h.IDADRDOC,
        h.DATECREAT,
        h.HEURECREAT,
        h.DATEMODIF,
        h.HEUREMODIF,
        h.DATEVALID,
        h.HEUREVALID,
        h.DATEENVOI,
        h.HEUREENVOI,
        h.DATELIMIT,
        h.DATETARIF,
        h.CODECON,
        h.CLASSCDE,
        h.ETATDOC,
        h.ETATMSG,
        h.DEVVENTE,
        h.CODEPROMO,
        h.IDTIERSPROMO,
        h.NUMSERIE,
        h.COMJADIMPR,
        h.COMCLIENT,
        h.LANGUEDOC,
        h.COMJADINT,
        h.FIXDEVISE,
        h.FIXTARIF,
        h.LIVAUTO,
        h.FACAUTO,
        h.SERVICE,
        h.SORTEVENTE,
        h.TYPEVENTE,
        h.MARQUAGE,
        h.IDTRANSIT,
        h.POIDSTOTAL,
        h.VOLUMETOTAL,
        h.POIDSAUTO,
        h.VOLUMEAUTO,
        h.TOTALTTC,
        h.TOTALHTBRUTP,
        h.TOTALHTNETP,
        h.TOTALHTNET,
        h.TOTALFOB,
        h.REFDOSJAD,
        h.IDPAYSDEST,
        h.DATEDEM,
        h.HEUREDEM,
        h.NATVENTE,
        h.SOUHAITLIV,
        h.FORMSOUHAIT,
        h.TOTALREMISE,
        h.TOTALTVA,
        h.TOTALEURO,
        h.TOTALFRAIS,
        h.TOTALACHATPEUR,
        h.TOTALACHATFEUR,
        h.TRANSPORT,
        h.INCOTERM,
        h.LIEUINCOTERM,
        h.PAYSINCOTERM,
        h.REFCLIENT,
        h.CDTREGLEMENT,
        h.MODEREGLEMENT,
        h.REFGARANTIE,
        h.TYPEFACTURATION,
        h.UTILISATEUR,
        h.LISTETARIF,
        h.TRANSIT1,
        h.IDTRANSIT1,
        h.IDADRTRS1,
        h.TRANSIT2,
        h.IDTRANSIT2,
        h.IDADRTRS2,
        h.NBJOURSECHEANCE,
        h.QUANTIEME,
        h.REGLEMENTCDE,
        h.PAYSCOMPTA,
        h.IMPRDISPO,
        h.IMPADRFAC,
        h.IMPADRLIVFINALE,
        h.IMPADRLIV,
        h.PAYSORIGINE,
        h.PAYSPROVENANCE,
        h.IMPCLASSECDE,
        h.IMPDISPO,
        h.IMPHTC,
        h.NUMLICENCE,
        h.LOILME,
        h.INSPECTION,
        h.CODEIMPUTATION,
        h.TITREDOCUMENT,
        h.IMPCOLIS,
        h.LANGUEDETAIL,
        h.CLASSEDOCUMENT,
        h.ETATVENTEPERDU,
        h.RAISONVENTEPERDUENTETE,
        h.NPS,
        h.CODEDATEVALEUR,
        h.DATERECEPTIONPO,
        h.DATERELANCE,
        h.NBRELANCE,
        
        /*
            LINES
        */
        l.IDDOCLIG,
        l.TYPEINFO,
        l.CODETRF,
        l.VRSTRF,
        l.TYPELIGNE,
        l.POSTENUM,
        l.POSTESUFFIX,
        l.IDLIGNE,
        l.IDLIGNEREF,
        l.REFPIECE,
        l.LIBELLE,
        l.CODECLASSE,
        l.BASECALC,
        l.COEFCLIENT,
        l.PXUNITACHAT,
        l.PXUNITLIST,
        l.PXUNITJAD,
        l.PXUNITBASE,
        l.PXTOTACHATEUR,
        l.PXUNITVENTEDA,
        l.PXTOTVENTEEUR,
        l.PXUNITVENTEDV,
        l.PXTOTVENTEDV,
        l.QTECLIENT,
        l.QTECDE,
        l.QTEANNULEE,
        l.QTERPL,
        l.QTEPACK,
        l.PXPACK,
        l.DEVACHAT,
        l.TAUXCHANGE,
        l.ORIGINELIGNE,
        l.LIGNEANNULEE,
        l.POIDSUNITAIRE,
        l.POIDSTOTALLIGNE,
        l.POIDSPACK,
        l.VOLUMEUNITAIRE,
        l.VOLUMETOTALLIGNE,
        l.VOLUMEPACK,
        l.CODEREMISE,
        l.COEFREMISE,
        l.TOTREMISEEUR,
        l.REMAN,
        l.ERRREF,
        l.CODEDISPO,
        l.QTECDETOT,
        l.QTECDEFRS,
        l.QTELIVTOT,
        l.QTEFACTOT,
        l.ITEMDELAILIVRAISON,
        l.ITEMDATELIVRAISON,
        l.TYPETARIF,
        l.REFPIECEERPCLIENT,

    /* =====================================================
       Métadonnées
       ===================================================== */
        'JPM'                                                AS application_code,
        'Jade Maurice'                                       AS source_module,
        'jade-piece'                                        AS sales_domain,
        CURRENT_TIMESTAMP()                                 AS dbt_processed_at,
        'silver_quote_part_mu'                                 AS dbt_model_name,
        '{{ var("silver_prefix") }}'                        AS layer_prefix

    from lines l 
    inner join header h
        on h.IDDOC = l.IDDOC
)

select * from silver_quote_part

